python mylatency.py -n 3 -d "1 Servers, 5 Containers" -o ../testlogs/sconf1_wconf1_.log
python mylatency.py -n 6 -d "1 Servers, 5 Containers" -o ../testlogs/sconf1_wconf2_.log
python mylatency.py -n 9 -d "1 Servers, 5 Containers" -o ../testlogs/sconf1_wconf3_.log
python mylatency.py -n 12 -d "1 Servers, 5 Containers" -o ../testlogs/sconf1_wconf4_.log
python mylatency.py -n 15 -d "1 Servers, 5 Containers" -o ../testlogs/sconf1_wconf5_.log
python mylatency.py -n 3 -d "2 Servers, 5 Containers" -o ../testlogs/sconf2_wconf1_.log
python mylatency.py -n 6 -d "2 Servers, 5 Containers" -o ../testlogs/sconf2_wconf2_.log
python mylatency.py -n 9 -d "2 Servers, 5 Containers" -o ../testlogs/sconf2_wconf3_.log
python mylatency.py -n 12 -d "2 Servers, 5 Containers" -o ../testlogs/sconf2_wconf4_.log
python mylatency.py -n 15 -d "2 Servers, 5 Containers" -o ../testlogs/sconf2_wconf5_.log
python mylatency.py -n 3 -d "3 Servers, 5 Containers" -o ../testlogs/sconf3_wconf1_.log
python mylatency.py -n 6 -d "3 Servers, 5 Containers" -o ../testlogs/sconf3_wconf2_.log
python mylatency.py -n 9 -d "3 Servers, 5 Containers" -o ../testlogs/sconf3_wconf3_.log
python mylatency.py -n 12 -d "3 Servers, 5 Containers" -o ../testlogs/sconf3_wconf4_.log
python mylatency.py -n 15 -d "3 Servers, 5 Containers" -o ../testlogs/sconf3_wconf5_.log
python mylatency.py -n 3 -d "4 Servers, 5 Containers" -o ../testlogs/sconf4_wconf1_.log
python mylatency.py -n 6 -d "4 Servers, 5 Containers" -o ../testlogs/sconf4_wconf2_.log
python mylatency.py -n 9 -d "4 Servers, 5 Containers" -o ../testlogs/sconf4_wconf3_.log
python mylatency.py -n 12 -d "4 Servers, 5 Containers" -o ../testlogs/sconf4_wconf4_.log
python mylatency.py -n 15 -d "4 Servers, 5 Containers" -o ../testlogs/sconf4_wconf5_.log
